### ISSUE TITLE
Header Content-Transfer-Encoding has been deprecated 

### ISSUE THREAD

**Issue by 61131** [lgtti/rfc7030-est-client#1]
This library currently requires the inclusion of a Content-Transfer-Encoding header in EST server responses. This header has however been deprecated by RFC 8951. This document identifies that the POST request and payload response of all EST endpoints should use base64 encoding and that format should be used regardless of any Content-Transfer-Encoding header. 

This was identified while testing against work-in-progress EST server module for nginx (nginx-http-server).

**Comment by lgtti** [comment]
Hi

This EST Client was not intended to be compliant with the RFC 8951 but I'm very happy to include this feature.
Thanks for your contribute!

After christmas I'll be able to check and integrate you code.

Lorenzo
