### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Bnz-0** [lgtti/rfc7030-est-client#4]
Following the tutorial in the README I noticed a couple of things:

First, in the examples it uses the file "dstcax3.pem" but there is written nothing on how get it.
```console
$ ./rfc7030-est-client -s testrfc7030.com \
    -p 8443 \
    --server-chain dstcax3.pem \
    --output cachain.pem \
    cacerts
```
My suggestion is to put a link to the http://testrfc7030.com site, which I found very useful, and maybe write as precondition the necessity to download the file by doing `wget http://testrfc7030.com/dstcax3.pem`.

Then I tried to use it as a library, by creating a static lib, but including the `src/lib/include` is not enough because `picohttp.c` requires `picohttpparser.h`
```
gcc -I src/lib/include  -c src/lib/picohttp.c -o src/lib/picohttp.o
src/lib/picohttp.c:2:10: fatal error: picohttpparser.h: No such file or directory
    2 | #include "picohttpparser.h"
      |          ^~~~~~~~~~~~~~~~~~
```
Which is a dependency that is written in the **Build** section but not in the 6.2.2 section, where there is the list of the folders you must include in the compilation.

**Comment by lgtti** [comment]
Hi, I will fix these comments in the next days
